- src/Plugin/Field/FieldWidget/StrawberryDefaultWidget.php
This is just a tiny helper for people editing raw JSON. 
This modifies the default Widget so it
1.- Will try to decode first. If that works, it will encode back with Pretty print enabled. 
2.- If it does not work, which is only a case for a corrupt DB, because we have Symphony Constraints in place when saving the field and also because our DB Schema is set for JSON (means we will never get there) output the erroneous original, not pretty printed, so people could eventually fix it.
> Pretty print JSON when editing RAW

- src/Form/keyNameProviderEntityForm.php
- src/StrawberryfieldFilePersisterService.php
Nothing really. Just a fix, i saw this weeks ago!
See #44 
others: Also, remove a dpm...
@giancarlobi @esmero/developers
> Fix active/inactive KeyNameProvider Form

- src/Plugin/StrawberryfieldKeyNameProvider/JsonldKeyNameProvider.php
See #51 
This adds a fallback retrieval strategy for URLs defined in our JSON-LD Key Name Providers. If we provide a default file, it will be used first instead of fetching the remote URL. IF we don't, one will be created and reused everytime the Database/Drupal cache is not longer valid. So double safe.
Checkout this branch
Clear Caches (have a coffee.. why is that so slow on Docker for Mac? Gosh)
Check if inside your Archipelago Git Folder (assuming its named archipelago-deployment) there is this another folder named `archipelago-deployment/web/sites/default/files/jsonld`
and if it contains two files
`36c4de8d45f712d0eaba5fd31d3a7fc9.jsonld`
`c20db5b6a8d641e98c0570d1ef89017f.jsonld`
The names are MD5 of the configured URLs in the JSON-LD Key name provider. 
Clear Caches again. …
> ISSUE-51: Use and Generate local copies of JSON-LD for Key Name Provider

- src/Plugin/DataType/StrawberryKeysFromJson.php
- src/Plugin/Field/FieldType/StrawberryFieldItem.php
- src/Tools/JsonSimpleXMLElementDecorator.php
Late night arrangements. Perfectionists one would say, but really is i totally want to avoid shame!
Adds the `JsonSimpleXMLElementDecorator` we had hidden for like 8 months! for our XML to JSON importer and adds 40 levels of decoding decoding goodness to deal with very deep XML elements (a.k.a EAD) while i figure out #94
>  ISSUE-94a: JSON decorator + matches webform_strawberryfield ISSUE-10b

- composer.json
- config/schema/strawberryfield.schema.yml
- src/Entity/keyNameProviderEntity.php
- src/EventSubscriber/StrawberryfieldEventInsertSubscriberDepositDO.php
- src/EventSubscriber/StrawberryfieldEventInvokeServiceSubscriber.php
- src/EventSubscriber/StrawberryfieldEventJsonProcessingSubscriber.php
- src/Field/StrawberryFieldEntityComputedItemList.php
- src/Form/FilePersisterServiceSettingsForm.php
- src/Plugin/Action/StrawberryfieldJsonPatch.php
- src/Plugin/DataType/StrawberryEntitiesViaJmesPathFromJson.php
- src/Plugin/Field/FieldType/StrawberryFieldItem.php
- src/Plugin/StrawberryfieldKeyNameProvider/EntityJmesPathNameProvider.php
- src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php
- src/StrawberryfieldFilePersisterService.php
- src/StrawberryfieldUtilityService.php
- src/Tools/StrawberryfieldJsonHelper.php
- src/TypedData/StrawberryfieldFlavorDataDefinition.php
- strawberryfield.module
- strawberryfield.permissions.yml
- strawberryfield.routing.yml
- strawberryfield.services.yml
A multi grain pull that started with the need of mass Metadata Editing.
Will add more details but now starting this pull so i can rebase this!
> Issue 101: JSON Patching, D9 fixes and new JSON Key name provider

- src/EventSubscriber/StrawberryfieldEventSaveSubscriber.php
- strawberryfield.module
This is a left over/not merged code of the original ISSUE-112. Nothing really new, just housekeeping
> little details to events: Priority + WACZ mimetype

- src/StrawberryfieldFilePersisterService.php
ZUPER FAST PROCESSING!
(excited)
See #125 
1.- We now depend on pdfinfo (shipped with our docker container and configured by default so all good.
2.- Identify will only run only on Images and Movies
3.- `pdfinfo` data goes into `flv:pdfinfo` instead of `flv:identify`. To be discussed since it makes twig templating more "obscure" for users? Still. This way se save some space on unnecessary 'format'. Existing Objects can easily patched via AMI.
4.- We store both rotation(in degrees) and Orientation (to be exif complaint)
@giancarlobi can you test this?
**This is also WAY faster now than with identify!!** 🥳 
On an AMI batch ingest with 8 PDFs and other 8 other Objects.
We passed from 550 seconds to 18.61 sec!!!!! Almost 1 second per Object. And we are talking about 128+ pages per PDF.
That …
> ISSUE-125: Use pdfInfo for PDFs and PostScripts

- src/Commands/HydroponicsDrushCommands.php
@DiegoPino Just a really draft idea to check if all queues are empty for at least 3 cycle. The 60 s timer check this and if all empty then close loop.
> Add idle time to close loop

- src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php
- src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php
See #134 
This works around this un-explicable edge case.
> ISSUE-134: check if SBF exists on previous revision before fetching flat version

- src/Tools/StrawberryfieldJsonHelper.php
See #148
Covers the basic needs. If the 'op' passed is a function, ones covered here will be only the ones using two arguments. No max()/min(), etc. We can not build a full parser. For more complex JMESPath filter expressions we will allow the user to also input a full custom string to cover those need. 
This is needed for
https://github.com/esmero/format_strawberryfield/issues/109
> ISSUE-148: Adds arrayToJMESPathfilterExpression helper method

- src/Controller/StrawberryfieldFlavorDatasourceSearchController.php
- strawberryfield.routing.yml
Super simple. Nothing fancy. See #159
> ISSUE-159:Adds a flavor count controller

- src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php
See #173 
This is bug fix. a missing else!
This is for sure the most busy part of SBF. Tested and all works correctly.
@giancarlobi in case you want to update. Merging is ASAP
> ISSUE-173: Make sure ap:entitymapping is generated even for plain manual RAW JSON

- src/Controller/StrawberryfieldFlavorDatasourceSearchController.php
- src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php
- strawberryfield.routing.yml
This is @giancarlobi work. I just did some small code cleanups. Tested and existing functionality is preserved but I need to merged other work first to test the new code. Code looks Ok to me (to be honest some of the ALTO/djvuXML things are unknown to me but I trust @giancarlobi knows better!
Will now move to format_strawberryfield and the strawberry_runners pulls that complement this one
> ISSUE-201: add Text Selection to OCR endpoint and Alto capabilities

- strawberryfield.install
Starts to resolve #228 
Additional commits to come.
> ISSUE-228: node_type deprecated and removed in Drupal 10

- src/Form/FilePersisterServiceSettingsForm.php
- src/Plugin/QueueWorker/CompostQueueWorker.php
See #240 
Tested, works well. Will merge ASAP
> ISSUE-240: Improve compost times and allow getTempDirectory() as safe path

- src/Controller/StrawberryfieldFlavorDatasourceSearchController.php
See #242 
Needed for https://github.com/esmero/format_strawberryfield/pull/252
> ISSUE-242: adds more data to Flavor Search result JSON

- src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php
See #247 and #244 
- The legacy OCR cleanup is a temp fix for WIP 1.1.0. Soon this will also be commited back into the backend AND will be only a workaround.
- The bug is(I am) stupid, instead of assigning the `$referencedEntity` to a new key i was retrieving a non existing key! December...
> ISSUE-247: Fix bug on parent of parent and cleanup empties for legacy OCR

- src/Tools/StrawberryfieldJsonHelper.php
See #249 
and also some minor indentation
> ISSUE-249: Fixes wrong use of static::

- src/Plugin/Action/StrawberryfieldJsonPatch.php
Resolves #251. Move simulate message to if simulate block and update message to match text-based action in AMI for consistency.
> ISSUE-251: Simulate message in StrawberryfieldJsonPatch in wrong place

- config/schema/strawberryfield.schema.yml
- src/Plugin/StrawberryfieldKeyNameProvider/EntityJmesPathNameProvider.php
- src/Plugin/StrawberryfieldKeyNameProvider/JmesPathNameProvider.php
- src/Plugin/search_api/processor/StrawberryFieldHighlight.php
- src/StrawberryfieldFileMetadataService.php
- strawberryfield.module
> ISSUE-253 + a bit of 246: New Highlight processor + Textarea for JMESPATHS

- src/Form/keyNameProviderOverviewForm.php
> ISSUE-268: Modern JS (latest 112.0.5615.121 (Official Build) (x86_64)) and our wonky #states bug

- src/Form/BreadcrumbSettingsForm.php
- src/StrawberryFieldBreadcrumbBuilder.php
See #270 
Super simple. Not much more to say
Thanks @alliomeria for asking for this
> ISSUE-270: Enable the shortest (third option) Tarth for breadcrumbs

- src/Plugin/search_api/processor/StrawberryFlavorContentAccess.php
See #279 
Basically adds:
`unpublished_any = $account->hasPermission('view any unpublished content');` and an if somewhere (note, after of course)
> ISSUE-279: View any unpublished content awareness for Search API Content access processor

- composer.json
- src/Event/StrawberryfieldCrudEvent.php
- src/Event/StrawberryfieldFileEvent.php
- src/Event/StrawberryfieldFlavourCrudEvent.php
- src/Event/StrawberryfieldJsonProcessEvent.php
- src/Event/StrawberryfieldServiceEvent.php
- src/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php
- src/EventSubscriber/SearchApiSolrEventSubscriber.php
- src/EventSubscriber/StrawberryfieldEventPresaveSubscriberVocabCreator.php
- src/Normalizer/StrawberryfieldFieldItemNormalizer.php
- src/Plugin/DataType/StrawberryEntitiesViaJmesPathFromJson.php
- src/Plugin/Field/FieldType/StrawberryFieldFileComputedItem.php
- src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php
- src/ProxyClass/StrawberryfieldMimeService.php
- src/StrawberryfieldFilePersisterService.php
- src/StrawberryfieldHydroponicsService.php
- src/StrawberryfieldMimeService.php
- src/StrawberryfieldUtilityService.php
- src/Tools/SimpleXMLtoArray.php
- strawberryfield.info.yml
- strawberryfield.module
- strawberryfield.services.yml
See #282 
Drupal 10 (and 9.5)
================================================================================
Strawberry Field, --
Scanned on Sun, 10/22/2023 - 17:05
No known issues found.
docker exec -ti esmero-php bash -c "./vendor/bin/phpcs -p ./web/modules/contrib/strawberryfield --standard=PHPCompatibility --runtime-set testVersion 8.1"
............................................................ 60 / 96 (63%)
.................S..................                         96 / 96 (100%)
Time: 2 secs; Memory: 26MB
All good to go. Now actually testing.Y ou know that interactions of UI/UX/data code means testing manually too.
> ISSUE-282:Macro Drupal 10 compatibility/PHP 8.1

- src/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php
- src/StrawberryfieldFilePersisterService.php
> ISSUE-291: Allow Early Rendering Wrapper to deal with both types of $controllers

- src/StrawberryfieldFilePersisterService.php
See #294 
I totally missed this one. Thanks @patdunlavey
> ISSUE-294: Fix missing access check on entity query

- src/StrawberryfieldFilePersisterService.php
> ISSUE-294: Fix missing access check on entity query 

- js/d3viz_strawberryfield.js
- src/Form/keyNameProviderOverviewForm.php
- strawberryfield.libraries.yml
> ISSUE-297: For 1.4.0, fixes once on D3JS

- src/Plugin/DataType/StrawberryValuesFromJson.php
- src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php
See #300 
@patdunlavey can you please test/see/look at the code and see if anything is amiss?
And if all works, approve? Thanks!
> ISSUE-300: Safer trim on JSON values from key name provider

- src/EventSubscriber/SearchApiSolrEventSubscriber.php
- src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php
- src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php
- src/StrawberryfieldRenderCallbacks.php
- src/StrawberryfieldSearchAPIUtilityService.php
- src/StrawberryfieldSearchAPIUtilityServiceInterface.php
- strawberryfield.module
- strawberryfield.services.yml
See #308 
and see #310 
and see #313 
@alliomeria this needs testing, but pretty useful for inclusive EADs where the free-form of dates contains a comma separated list of ranges.
> ISSUE-308: This adds {1992..1996,...} to Solr indexing + Session ISSUE-310 + ISSUE-313

- src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php
And poly-juice transmutation for the people
See #322
> ISSUE-322: Add the famous universal constant of time/space disambiguation

- config/schema/strawberryfield.schema.yml
- src/Plugin/search_api/processor/Property/StrawberryFlavorAggregatedItemProperty.php
- src/Plugin/search_api/processor/StrawberryFlavorAggregate.php
> ISSUE-336: Adds SBF ADO NID configuration (source/join) for Flavor Aggregated Processor Field

- src/Plugin/search_api/processor/StrawberryFieldHighlight.php
@alliomeria that message i shared.
see #340
> ISSUE-340: Fixes grouping issues on Search API Advanced Highlights

- src/Commands/JsonApiDrushCommands.php
> ISSUE-342: Update Drush JSON API to Drush 12+/Drupal 10

- config/schema/strawberryfield.schema.yml
- src/Commands/HydroponicsDrushCommands.php
- src/Form/HydroponicsSettingsForm.php
- src/Plugin/Action/StrawberryfieldJsonPatch.php
- src/Plugin/QueueWorker/CompostQueueWorker.php
- src/StrawberryfieldHydroponicsService.php
See #352 #350 
This cleans up hydroponics, adds some more verbose logging, adds Search API Indexing capabilities to background processing also cleaning some basics on the composter.
There is also a small cleanup open the JSON PATCH action to be more verbose when running via AMI (but independent)
> ISSUE-352 and ISSUE-350: Composer improvements/logging and new Search API Hydroponics indexer
