src/Plugin/DataType/StrawberryDataByKeyProvider.php, src/Plugin/DataType/StrawberryKeysFromJson.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, src/Tools/StrawberryfieldJsonHelper.php, strawberryfield.install, strawberryfield.module
This commit adds a few nice JSON key processing
- Finally, a working itemList data type computed property that Solr can see. Had
to work around the precomputing of initial `$list` values, since Drupal's Solr Module uses iterators instead of `getValue()`
- A JSON Path extractor, generator from data/metadata capable of detecting lists and named properties to add wildcards to paths. Used as a computed property in any
strawberry field (property name: `str_flatten_keys`). Actual method is found at `\Drupal\strawberryfield\Tools\StrawberryfieldJsonHelper::arrayToFlatJsonPropertypaths`. Wildcard conversion works by detecting if a substructure is of type:
- Object (or associative array when casted) or 
If Object and keys are URI, assume those are identifiers (in a semantic way) or at least can …
=> Improved JSON key logic

src/Plugin/StrawberryfieldKeyNameProvider/JsonldKeyNameProvider.php, strawberryfield.module
Our JSON-LD Strawberryfield dynamic properties provider allows for extra, coma separated, list of properties. Make actual use of this.
=> Allow for extra Keys even when using external schemas

src/Plugin/DataType/StrawberryValuesFromJson.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, src/Plugin/StrawberryfieldKeyNameProvider/JsonldKeyNameProvider.php, strawberryfield.install, strawberryfield.module
With Solr Search API 3.x-dev out and https://www.drupal.org/project/search_api_solr/issues/2828441 fixed we can now index our multivalued properties from Strawberry fields properly.
This pull adds:
- A new property value provider based on our Key plugins that returns a List of values. This allows of much better Views Integration, Faceting, etc. You name it
- Trims exposed property values, because Search API on one side indexes values as they are (even with leading spaces, and that is OK) but then cleans the spaces on Faceting display making faceted refining die on you.
- This Pull also brings some improvements on the already awesome Vocabulary Generation: preparing for a new JSON KEY provider to expose Strawberry fields that will use actual JSON PATHS collected from this vocabulary to ket …
=> Strawberry field properties exposed to Drupal properly as a list of items

src/Normalizer/StrawberryfieldFieldItemNormalizer.php, src/Plugin/DataType/StrawberryValuesFromJson.php, src/Plugin/Field/FieldWidget/StrawberryDefaultWidget.php, strawberryfield.services.yml
- Core Update 8.6.13 removed a trait from parent class in our widget. So add the Trait and make sure we access now the public method instead of the private property: $this->messenger()
- Individual properties of a StrawberryField (the ones we expose from the full JSON using our Key name providers plugins) are now less nested to allow Serializer/normalizer to expose the values. This still requires more work since we could be eventually (i double checked but hey, its difficult) nested arrays. I will use an iterator to fully flatten anything in case that is the case in https://github.com/esmero/strawberryfield/blob/master/src/Tools/StrawberryfieldJsonHelper.php#L86
- Stub work on adding a normalizer that will take care of the main value of a strawberryfield. This is just stub now and does …
=> Coping with Core changes and WIP for allowing Strawberryfield to be normalized and exposed

src/Field/StrawberryFieldItemList.php, src/Plugin/DataType/StrawberryKeysFromJson.php, src/Plugin/DataType/StrawberryValuesFromJson.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, src/Plugin/Field/FieldWidget/StrawberryDefaultWidget.php
Main issue here is how Drupal 8 decides which widget to show when setting a field inside the Content Type Admin menu. There you can set default values, etc, but if a special $form_state key is not present *which can be only set via a form alter and is not used anywhere i core* if will render the widget used in the default form display to set The defaults. That is in our case totally wrong, we don't want to set a default JSON via a webform in this context (and it also does not work).
Since our StrawberryField Field uses mostly computed Properties i wanted to improve computing times. We now use much more ::computed to check instead of going into ::processed content on each property. There are tiny changes here, but it will drop a few extra cycles if the main property of the field is empty …
=> Make sure we have a default widget during field instance setup

src/Normalizer/StrawberryfieldFieldItemNormalizer.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, strawberryfield.services.yml
Related to #11  (which is almost the same but in other words)
This pull allows our JSON encoded Strawberryfield to be expanded into a full array (and then serialized as it needs to) for REST, API and in general Symfony and Drupal serialization needs. This is another step into having a fully functional strawberry seeds module. Now we can export Full Objects with all its JSON and store it in a file, expose it via REST and other build in APIs. 
In a functional Archipelago with at least an Digital Object select one of the following options:
enable the php devel module (removed from dev core for obvious security reasons) and run
```PHP
use Drupal\node\Entity\Node;
$serializer = \Drupal::service('serializer');
// replace Node::load(1); with any actual node id
$node = Node::load(1);
$data = …
```
=> Implements a StrawberryField Item Normalizer 

src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
This pull brings some small changes, but it looks like a lot because of the removed lines and some shifting lines done because of the Dependency injection.
1. Adds a configuration form
2. Adds ::getApplicableBundlesWithSbfField() which filters for node bundles  that have a SBF field type field
3. Makes ::getBundles aware of getApplicableBundlesWithSbfField
4. Injects some services from the Main container in the ::create method
@giancarlobi please look at this and let me know if this works. I will be adding more code during the day to the same pull, and you can of course do the same (or request changes, etc)
looking at how much code we are duplicating from `\Drupal\search_api\Plugin\search_api\datasource\ContentEntity` maybe we should think in the near future to extend that class instead …
=> Refactor StrawberryfieldFlavorDatasource to allow Node bundles

src/Annotation/StrawberryfieldKeyNameProvider.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
@giancarlobi the change was so simple.
`\Drupal\Core\Entity\Plugin\DataType\EntityReference::setValue` accepts also just the integer (id) of the entity! You can eventually pass a loaded entity but we don't want over processing =) So rolling this back to your original way of setting the value but with the better data definition we have now (which means we don't need to load the node, just pass $splitted_id[0]!) does the trick!
I added the parent node's UUID and i got this document ("ss_uuid":"1d4aae51-c06b-402c-8bba-9094c0b792f3")
```JSON
[{
"id":"m7pu9i-default_solr_index-strawberryfield_flavor_datasource/9:4:en",
"ss_parent_id":"9",
"ss_page_id":"4",
"ss_search_api_id":"strawberryfield_flavor_datasource/9:4:en",
"sort_X3b_en_parent_id":"%\u0000",
"index_id":"default_solr_index", …
```
=> Fully functional parent Node indexing!

src/ParamConverter/UuidEntityConverter.php, strawberryfield.services.yml
See #47 
To see this in action, momentary (until we merge all). fetch and checkout this branch https://github.com/esmero/strawberryfield/tree/ISSUE-47
in the format_strawberryfield module
either:
A)
edit `format_strawberryfield.routing.yml` and replace 
format_strawberryfield.metadatadisplay_caster: with
```YAML
format_strawberryfield.metadatadisplay_caster:
path: '/do/{node}/metadata/{metadataexposeconfig_entity}/{format}'
methods: [GET]
defaults:
_controller: '\Drupal\format_strawberryfield\Controller\MetadataExposeDisplayController::castViaTwig'
options:
parameters:
node:
type: 'entity:node'
metadataexposeconfig_entity:
type: 'entity:metadataexpose_entity'
resource_type:
type: 'ado'
requirements:
format: .+
_entity_access: 'node.view'
```
or B)
Test with …
=> ISSUE-47: UUID node up-caster for Routes that have as parameter 'ado' as resource_type

config/schema/strawberryfield.schema.yml, src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php, src/Plugin/StrawberryfieldKeyNameProvider/JmesPathNameProvider.php, src/Plugin/StrawberryfieldKeyNameProviderManager.php, src/Tools/StrawberryfieldJsonHelper.php
See #46. This is just one of the listed there. But we are moving forward.
This is just good, lovely and needed. 
This pull provides the following new options:
1. A new JSON Key Name Provider Plugin that deals with JMESPath processing to populate a given Strawberryfield exposed property (For Solr). This Plugin allows a comma separated string of JMESPaths, which means we can take a few different values from all over the JSON and expose them as a single Solr Field/Facet. This also gives us the change to target pretty specific values in a complex hierarchical JSON.
2. A New `DataType` extended from `itemList` matching the new Plugin. It does some smart things like checking if the JMESPath results are actually just an array of values or a Multidimensional Array. In the later case, it …
=> ISSUE-46: Provide a JMESPath option to expose parsed results as a Field property

config/schema/strawberryfield.schema.yml, src/Form/ImportantSolrSettingsForm.php, src/StrawberryfieldUtilityService.php, strawberryfield.links.menu.yml, strawberryfield.routing.yml, strawberryfield.services.yml
Addresses #53 
This push addresses the first part only of #53, creating the form to save the new config.
- Add schema for strawberryfield.archipelago_solr_settings. For now it only holds type related config
- Add route to /admin/config/archipelago/important-solr-settings
- Add ImportantSolrSettingsForm.php
This is the most code in this file. I don't know if it is the optimal UI, with multiple dropdowns, but it works pretty well for me.
Go to /admin/config/archipelago/important-solr-settings and follow the form
I created extra Servers and Indexes to make sure all the conditional switching worked.
Not sure how you want to deal with no config set. I am guessing, @DiegoPino since you were going to deal with the second part of #53 , that you might set default config.
=> ISSUE-53: Create new Config page for Solr settings

config/schema/strawberryfield.schema.yml
See #57 
This pull adds the basic configs needed for our SB Flavor Data Source Provider Plugin (Search API) to pass any configuration sync sanity (except mental) checks.
Nothing to see here. This supports this code https://github.com/esmero/strawberryfield/blob/8.x-1.0-beta2/src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php#L451-L501
=> ISSUE-57: Add a schema for our SBF Flavor data source plugin

config/schema/strawberryfield.schema.yml, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php, strawberryfield.services.yml
See #55 
This adds a quite naive service that allows Nodes without a visible Title Field during Ingest to use a SBF 'label' key as Title for the node, avoiding also the fact that Drupal 8 totally allows you to hide the field but knows little what to do after the fact and dies with a shiny white page with constraints failures (or course, since title is a primary entity key).
We also, smartly truncate the SBF label, a.k.a title since Drupal's Title field length by default is 128 Chars and that is not really enough for metadata, right people? Means, our Metadata title will always be richer and cooler.
Anyway. We also provide (since we are here) our SBF Flavor Datasource Schema, which was missing or really, was == as any other Content Data source == and was already commited in #57, but i was …
=> ISSUE-55: Title setter Service based on Metadata 

src/StrawberryfieldFilePersisterService.php
See #60 
This is a quite simplistic automatic sequencer (🎧...not that type of sequences) based on natural ordering of file names that lives on our File Persister Service. It will always kick in on Edit/Ingest, so we need to come up with solutions that don't interfere with forcer/manual ordering, if that is the case. It just adds a `sequence` key to our `as:filetype` JSON structure and its corresponding value after an `uasort` using natural string comparison.
I just came (while writing this) with two additional ideas, additional (and not excluding) to the ToC  (Table of Content or index) and the _'i don't know what i'm doing_' 🙄 i stated in the issue:
1.- If the current order, is already _totally not_ in Natural Order, but `sequence` keys with values are present, when assume its manually …
=> ISSUE-60: Automatic Natural order for uploaded files

src/Tools/StrawberryfieldJsonHelper.php
Move Array ordering/sorting out of formatter into a static method in our JSON helper class.
https://github.com/esmero/format_strawberryfield/pull/41 introduced a bug (because not every formatter extends our base formatter and i'm sleeping) so a good opportunity to also make that one better by moving this function totally out of our formatter.
Been giving the thought that the SBF field itself could expose a computed property that orders and decodes the JSON string into an array, maybe for Beta3
=> ISSUE-61: Make orderSequence a Static method of StrawberryfieldJsonHelper

src/Normalizer/StrawberryfieldFieldItemNormalizer.php, src/Tools/StrawberryfieldJsonHelper.php
This addresses #11 
Not much code. It took me some studying to understand this system in Drupal. The best article I read was [here](https://www.dx-experts.nl/en/blog/2017/drupal-8-hal-json-rest-mechanisms) even though it is specifically about hal json.
Now we can accept expanded JSON content in an SBF via POST, and create a valid new Node bearing the SBF. POST can accept either stringified or expanded JSON for SBF.
This section will look really long, because of pasted-in JSON. But it is not actually scary.
1. Clear cache because we have new services. Then go to `/admin/config/services/rest`. Make sure POST is enabled for node and enable the format `hal_json`. 
2. Below is a big old JSON taken from our minio storage. I was encountering permission problems creating new nodes, for the …
=> Issue-11: Allow denormalizing of encoded JSON in Strawberryfields

src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php
See #69 
While testing Beta2 i saw some inconsistencies while setting the ADO/NODE label when the Webform itself had the Title Label hidden (like we do in our default Webform for the deployment) and the Main Node title element was visible. That triggered on a first ingest an edge case where there was actually a title and none in the metadata and we ended with our default, save the queen, version of a generic title. This tiny pull fixes that. Tested with
1. Form mode with NODE title visible and webform Title invisible
- Create
- Edit
2. Form mode with NODE title invisible and webform Title invisible
- Create
- Edit 
3. Form mode with NODE title invisible and webform Title visible
- Create
- Edit
4. Form mode with NODE title visible and webform Title visible
- Create
- Edit
In all cases i …
=> ISSUE-69: Fix title setter, add some conditionals to deal with edge cases

config/schema/strawberryfield.schema.yml
This pull addresses #71 
It adds schema for `field.widget.settings.strawberry_textarea`
=> Issue-71: Add missing schema

config/schema/strawberryfield.schema.yml
This addresses #71 (as did #72)
@DiegoPino I found more schema errors relating for this module :)
This fixes the missing schema error for 
`default_value.0.value` in `field.field.node.digital_object_collection.field_descriptive_metadata` (or any other field of type strawberryfield_field)
New schema in `config/schema/strawberryfield.schema.yml`
According to my searching, this missing schema seems to be a common error when creating custom field types in Drupal, so don't forget to add it next time :)
=> Issue-71b: Add schema for strawberryfield_field itself!

src/EventSubscriber/StrawberryfieldEventInsertSubscriber.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriber.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberVocabCreator.php
See #80 
Change `self::` for `static::` to allow late binding of properties in subclasses (sounds like subatomic physics.. but its not)
Rememer kids, the lower the number, the later in time the execution is pushed:
priority 1 runs before -2000
=> ISSUE-80: Change self:: for static:: and adjust priorities

src/EventSubscriber/StrawberryfieldEventDeleteFileUsageDeleter.php, src/EventSubscriber/StrawberryfieldEventInsertFileUsageUpdater.php, src/EventSubscriber/StrawberryfieldEventInsertSubscriberDepositDO.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberFilePersister.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php
Basically, don't tell the user everytime it saves a Node/ADO via a Webform that the title changed if its still the same. Mostly cosmetic, but was driving me insane. Also, if the change happened with an actual title field visible and not only driven by webform, don't notify the user because the Event Subscriber basically does nothing (sets Force Update to false and skips the logic, good)
@giancarlobi @mitchellkeaney this is just a heads up so you know i did this. Will merge later today
=> ISSUE-84: Only notify user of Metadata driven title change if change is noticeable

composer.json, src/Event/StrawberryfieldCrudEvent.php, src/Form/keyNameProviderEntityDeleteForm.php, src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php, src/Plugin/Field/FieldType/StrawberryFieldFileComputedItem.php, src/Plugin/StrawberryfieldKeyNameProviderInterface.php, src/StrawberryfieldFilePersisterService.php, strawberryfield.info.yml, strawberryfield.module
See #90 
Most of this is just housekeeping, changing some deprecated calls, interfaces and legacy code to be D9 ready. Still, there is a confusing issue (not us, them) regarding Symfony >=4.3 and now Events are being dispatched that makes no sense to me.
So Symfony 4.3 moves Events to a new Interface. And then also changes how the dispatch is done (the order or arguments). I did the chances and of course all died. And then checked D9 and D9 is still using the old versions (can anyone confirm?) for both, even if they are on 4.4 already. So deprecated code??
Anyway. I managed to open an issue here: https://gitlab.com/drupalspoons/devel/-/issues/329 (and i also have now an account there... how many gosh)
- Since i was also doing housekeeping there is a small formatting fix for the benchmark …
=> ISSUE-90: Final commits for D9 readiness/spiciness

src/Commands/JsonApiDrushCommands.php
And so it happens, when you are about to release you find an edge case that breaks what works.
- JSON needed more escaping to allow complex things to be used by curl as --data
- More `@Throws` (not dishes, just exceptions) to make sure no ingest happens if JSON is invalid, missing, etc
- Being a decent Citizen and making sure PHPDOCS are Ok enough
=> Issue-91: JSON API last minute fixes

src/Commands/JsonApiDrushCommands.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/Plugin/DataType/StrawberryKeysFromJson.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/Tools/SimpleXMLtoArray.php, src/Tools/StrawberryfieldJsonHelper.php
This pull adds new XML to JSON processing strategy in addition to the JSON encoding decorator we had. Deals with Namespaces in correct way and also allows certain path based functions to be exclude from our calculations so we don't store of process hundreds or thousands of JMES-JSON paths in our vocabulary. 
- Also fixes issue with our ingest drush command `jsonapi-ingest` (needs a refactor for 1.0.0, want to move our of `curl` to the internal `httpclient`) not reading/uploading files with filenames containing spaces which leads to a 0 byte upload.
=> Issue 10c: Adds new XML to JSON processing strategy and a fix for Drush ap:

src/Commands/JsonApiDrushCommands.php, src/EventSubscriber/StrawberryfieldEventDeleteFileUsageDeleter.php, src/EventSubscriber/StrawberryfieldEventInsertFileUsageUpdater.php, src/EventSubscriber/StrawberryfieldEventInsertSubscriberDepositDO.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberFilePersister.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberVocabCreator.php, src/Plugin/Action/StrawberryfieldJsonPatch.php, strawberryfield.permissions.yml, strawberryfield.services.yml
See #109 
This adds 
- A new permission
- A check of that permission every time we want to be verbose in SBF during a EventSubscriber
Reducing that way our dB/verbosity a lot and allowing non REPO aware avoid unnecessary burdens and deep knowledge of the ADO creation process.
How to test? Log in as the DEMO user and create a new ADO. Only Content creation message should appear, do the same as ADMIN, a bunch of tech-buzz-word stuff will pop up reassuring  your process was successful!
Also added. Now the JSON Patch Action that is used (with a form) by AMI has a simulation mode. I love simulation modes where nothing gets modified and we can watch how a JSON Patch affects metadata without harm.
=> ISSUE-109: Verbosity on demand

src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
See #112 
Fixes SBFlavor DataSource Indexing for good and adds some extras:
- Better checking if file still exists (in case someone decides to delete before we even get a change to run this)
- Passes from the processor (via key value) the checksum
- No more overwriting previously existing Solr Docs
- Data Type (SBFlavor) has more data now, checksum, node uuid, file uuid and a file entity reference in case we want to save stuff like the file name, the source, etc that originated this. I also added a URI/URL field/prop so we can also index things like URLs for HTML pages (WACZ)
=> ISSUE-112: less shame, more Solr Indexing

src/Controller/StrawberryfieldFlavorDatasourceSearchController.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/StrawberryfieldFilePersisterService.php
See #121 
- Simple  public function `calculateAsKeyFromFile(FileInterface $file)` that uses the `mimetype` to get the `as:filetypes`, etc keys. Code was already there but since we needed to reuse it I made a method
-  Moved all mentions of 'as:' and 'urn:uuid' to CONSTANTS in the class. Cleaner, better.
-  New method that given a list of file ids removes any entry of those from the JSON inside the as:structure
public function removefromAsFileStructure(). I also, once removed decreases the Usage count since no other service has actually access to that info. And this is the right moment to do so. 
- Singe 1 count removal is applied using `$this->remove_file_usage($file, $nodeid, 'node', 1)` 
- Returns the original FULL JSON (not the previous one) with `as:filetype` entries removed.
PS: …
=> ISSUE-121: Make file deletion / removal of as:structures better

config/schema/strawberryfield.schema.yml, drush.services.yml, src/Commands/HydroponicsDrushCommands.php, src/Form/HydroponicsSettingsForm.php, src/ProxyClass/StrawberryfieldMimeService.php, src/StrawberryfieldHydroponicsService.php, src/StrawberryfieldMimeService.php, strawberryfield.links.menu.yml, strawberryfield.module, strawberryfield.routing.yml, strawberryfield.services.yml
See #127
First one: This method is not provided by Drupal. There are a few modules that do this, but then they do not use the already existing alters. So better this way. This is the way 👶 
Second One: reactPHP and Drush working together to grow Strawberryfields without ground/dirt. Hydroponics Service/Background processor and settings/configs. A dream come true. Still, EXPERIMENTAL as hell. But its working well.
- It provides a Simple Form where Queues can be set as being managed by Hydroponics processor and a general /active/inactive key
- Adds a Cron hook (for now) that will check if there is a process, if the process is running and if not will exec via `nohup` a drush script and direct logs to /tmp/hydroponics.log. This may need to be better. We can, in theory send logs out to Docker …
=> ISSUE-127: Adds a reverse Mime type guesser and the Hydroponics Background processor!

src/Tools/StrawberryfieldJsonHelper.php
See #136
Using constansts to iterate over filetype is "better" and "cleaner" did he say.
Because as:model was missing once we removed the webform processing 3D Models stopped being classified. This is on me. ONLY ME!!! @alliomeria need to update hashes all around.
@alliomeria @giancarlobi
=> ISSUE-136: Big bad BUG on as:filetype

config/schema/strawberryfield.schema.yml, src/Plugin/DataType/StrawberryEntitiesViaJmesPathFromJson.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, src/Plugin/StrawberryfieldKeyNameProvider/EntityJmesPathNameProvider.php, strawberryfield.install
1.- It gives StrawberryEntitiesViaJmesPathFromJson Key Name provider a new setting so which entity type is being extracted can be set. All JMESPATHs selected in a single Key Name Provider configuration using this plugin need to be of the same type. 
2.- Changes the way we load Entity References as Exposed Properties of a StrawberryField Item, allowing many and still permitting Search API to index individual fields of the referenced entities of even the whole hierarchy (using the processor, this last one is a not proven statement but also not something I may want to promise for this ISSUE)
3.- Updates the schema for the plugin and adds Hook update so existing Key Name provider entities get "node" as default entity selected
Check this branch out. Remove your existing Search API fields using …
=> ISSUE-143: Allow additional Drupal Entities to be extracted by StrawberryEntitiesViaJmesPathFromJson key name provider

src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/StrawberryfieldFilePersisterService.php
#151
Instead of reaching out to the original entity SBF field values(if any) we use the flat version of the current SBF to fetch all `dr:fid` (referenced File IDs). We also fetch `dr:for` (source Keys for those field ids) to make sure we can, in case of "emergency" rebuild our file mapping from there and we do if that is the case (new)
We compare effectively File IDs inside `as:filetype` with File IDs provided in user contributed Keys found in the `ap:mapping` structure (in that order). If there are differences, those differences are File IDs that do not longer exist/were not provided by the user. We clean those up from the `as:filetype` and also check  (new) if there are Files that do not longer exists in Drupal (edge case but can happen if you copied a full JSON between repos) and clean …
=> ISSUE-151: Another different and better way of clearing/managing of `as:structures`

src/StrawberryfieldFilePersisterService.php, src/StrawberryfieldMimeService.php
#What is this?
A different approach on getting the mimetype of an extension by accumulating all matches and returning the last one. If it is of course  slower because but we call this only during ingest.
See #153
@pcambra @patdunlavey @giancarlobi please look at this and fight me back. If not I will merge because I need precise warc.gz files!
=> ISSUE-153: Deal with multi dot extensions (warc.gz, tar.gz) 

src/Controller/CustomNodeEditController.php, strawberryfield.routing.yml
This PR makes use of getFormModeOptionsByBundle among other cleanup tasks
Resolves #156
=> ISSUE-156: Custom Edit Route when "use default" is disabled fails to check if form mode is enabled

src/Controller/CustomNodeEditController.php
Well I should have double checked the code. My bad
PS: And now i know why i do not like array filters 😆  (I do like them.. but I fear them)
The array filter was using the value, the value is not a machine name so all permissions where failing. This adds ARRAY_FILTER_USE_KEY we have the actual form mode.
Also. My IDE's Drupal (verified I'm using the right now, I promise) DCS is putting long lines with method accessors in a second row. I hope this is the right thing... do I need to check again?
=> ISSUE-156(second pass). Fix wrong array_filter

src/EventSubscriber/StrawberryEventSaveFileDeleteFlavorSubscriber.php, src/Field/StrawberryFieldFileComputedItemList.php, src/StrawberryfieldEventType.php, strawberryfield.module, strawberryfield.services.yml
- New service that reacts on the entity update, to check if a file has been removed, if it's the case, it issues a tracking delete on search api for the flavours affected (OCR only).
- Adds a check on the interface for `EntityPublishedInterface` when `isPublished` is checked on `strawberryfield_invalidate_fieldefinition_caches`
- Documentation and style fixes along the way in other files
Resolves #123
=> ISSUE-123: Add SOLR SBF Flavor Document removal when File gets removed

src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, strawberryfield.module
See #171 and #170 
This adds a constant for empty miniOCRs that can be used by runners or any other (e.g an XML OCR endpoint) and also ensures that we do Access Control on Parent Node.
And extra Search API query option was added (`no_highlight`) to help in cases where we want to programatically call a Solr query, get all Fulltext fields but do not want HL enabled, because without an exact Fulltext field ocrhighlight, as documented, will fail with an "invalid offset" error Solr side.
@giancarlobi you probably need this to test #170
=> ISSUE-171: Adds en empty miniOCR as constant and ensure Access Control

composer.json
See #177 
Version 0.1.0 does not longer exists. That is really bad behavior of that package and they have moved 2 versions in 2 months. Let's catch up. 
Our use is still very discrete so this is not breaking
@patdunlavey thanks for reporting. Can you check this change and approve if you are OK?
=> ISSUE-177: Update professional-wiki/edtf version to 2.0

composer.json, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/Field/StrawberryFieldEntityComputedItemList.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, src/StrawberryfieldFilePersisterService.php
See #180
New method`::sortFileStructure` for the StrawberryfieldFilePersisterService Services. Gets invoked by the File Structure Generator presave Subscriber.
ADOs SBF JSON's accept now this extra key
```JSON
{
"ap:tasks": {
"ap:sortfiles": "manual"
}
}
}
```
ap:sortfiles can be:
*  manual (new files will be appended at the end, order of upload is preserved but any manual order given by the user is preserved too)
* natural (files old and new are always sorted by name of the file inside the as:key"
* index (files old and new are always sorted by the order of appearance in their respective "source keys", e.g documents, etc (same as show during a webform based edit). Same applies for AMI uploaded files.
Also bumps PHP requirements to >= 7.2
How to test?
- Create a new ADO. Upload a bunch of …
=> ISSUE-180: Refactors ordering for Files +  Minor Computed field fix

src/EventSubscriber/StrawberryEventDeleteFlavorSubscriber.php, src/EventSubscriber/StrawberryEventSaveFlavorSubscriber.php, src/Plugin/DataType/StrawberryfieldFlavorData.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/Plugin/search_api/processor/StrawberryFlavorContentAccess.php, src/StrawberryfieldFilePersisterService.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php, strawberryfield.services.yml
See #184 
`Label` and `Metadata`, `ts`, `url`, `sentiment`, `who`, `where` and `when` are the new ones. Will come handy in the future (near future)
Will test if original functionality is not affected and will go from there. This is the first step into RC3 and will also include once tested the new reactPHP code Giancarlo did to enhance the experience
Also includes Access Control processor (replacement for the Core one) that knows how to handle Strawberry Flavors (so full status connection between Nodes and its HOCR) and some extra goodies like automatic updates on Strawberry Flavor Solr Indexed Documents(HOCR when the Node changes user/status).
This comes with an extra pull from Strawberry Runners but does not require it.
=> ISSUE-184: Adds new data properties to Class StrawberryfieldFlavorDatasource and provide custom Access Control

src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php
As @alliomeria and I discovered today, if your webform has actual ISO8601 dates formatted (storing in JSON) the EDTF formatter will kinda give up. This better approach (which I'm sure I coded already in the past but can't find where/how? why am I so tired all the time?) tries in case of an EDTF failure with a direct PHP string to Date approach. How?
- First we try assuming the date is already ISO8601 ('c' format). Why? because in the next step I will convert all into a UNIX Timestamp and as you well know Unix TimeStamps have no Time Zones (and ISO8601 has).
- If this fails we check if not numeric. Why? because next step deals with all except with timestamps. 
- If not numeric we go with a strtotime() which will accept things like "yesterday", "tomorrow", "2022", "1917-01", etc. and will …
=> Issue 175b: make date/time parsing even more flexible in our JmesPath keyname provider

src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php
also includes fix for cases when the jmespath_result is not a string (when the value in the field was json_decoded to an array).
See discussion here: https://github.com/esmero/strawberryfield/issues/207
=> ISSUE-207 --- proposed fix for EDTF parsing problem with open range interval dates

config/schema/strawberryfield.schema.yml, src/Commands/HydroponicsDrushCommands.php, src/Form/HydroponicsSettingsForm.php, src/Plugin/Action/StrawberryfieldJsonPatch.php
See #210. Yes my branch is incorrectly named, but Github crashed, not my fault! (well it is my fault)
This adds a Time To Live argument for Hydroponics. When set to 0, it will process until all queues are done, no exception. The default value is still 720 seconds as before and can be modified in 60 seconds increments. Also updates how the loop is created removing a deprecated factory:: call.
Additional. Forces revisions on JSON Patch derived operations.
=> ISSUE-210: add timeout argument to Hydroponics

composer.json, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberInvalidateParentCaches.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php, src/StrawberryFieldBreadcrumbBuilder.php, src/StrawberryfieldFilePersisterService.php, strawberryfield.services.yml
See #213 
Also includes PHP8 (smaller) fixes and a more flexible dependencies matrix
=> ISSUE-213: Related ADO cache tag invalidation

src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/StrawberryfieldFileMetadataService.php, src/StrawberryfieldFilePersisterService.php
See #215 
This adds a new remote S3 head/check if there/checksum method that does not depend on S3FS caching.
We also flatten mediainfo response immediately in case we need to do a JSON PATCH in the future (swagger/json* diff and stuff can only act on native JSON and not PHP objects that implement to array methods (Thanks @patdunlavey for finding this)
Finally we ALWAYS take over files that live in temporary:// independently of their status. This will allow temps to be set as permanent and still be managed/counted/moved by SBF
=> ISSUE-215: Add S3 remote check and improve mediainfo/flattening + sanity

src/EventSubscriber/StrawberryEventSaveFlavorSubscriber.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
See #217 
Also. This enables 2x new properties that can go into Solr, `nlplang` and `processlang`
- `nlplang`: Language detected during OCR/WACZ page extraction
- `processlang`: Language requested from defaults or metadata for OCR
=> ISSUE-217: Fixes non sense logic for updating/removing left over SBFlavor docs

config/schema/strawberryfield.schema.yml, src/Event/StrawberryfieldFileEvent.php, src/EventSubscriber/StrawberryfieldEventCompostBinSubscriber.php, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php, src/Form/FilePersisterServiceSettingsForm.php, src/Plugin/QueueWorker/CompostQueueWorker.php, src/StrawberryfieldEventType.php, src/StrawberryfieldFilePersisterService.php, src/StrawberryfieldHydroponicsService.php, src/Tools/StrawberryfieldJsonHelper.php, strawberryfield.api.php, strawberryfield.services.yml
See #222 
This pull adds:
- New EventType and Event Subscriber. Event is triggered during and ADO's file persistence and when we are sure it happened. The Subscriber fills a queue.
- The queue worker checks if the file is there, if its safe, if its not used by an Entity, if it has been longer or === than the max time to live and deletes it. If all matches, except time it re-enqueues (Double check Hydroponics since we are using a new D9 Class here)
- There is also a hook that allows other modules to inform where/what is safe.
- There is also a new Config to be seen at `/admin/config/archipelago/filepersisting`
The queue needs to be configured to Run hopefully using Hydroponics but testing can be also done via the System Queue manager.
Other modules (e.g SB Flavors) will invoke the event …
=> ISSUE-222: Composer bin service. Enqueue and delete temp files

src/Controller/StrawberryfieldFlavorDatasourceSearchController.php, src/EventSubscriber/StrawberryEventSaveFlavorSubscriber.php, src/Field/StrawberryFieldEntityComputedItemList.php, src/StrawberryfieldUtilityService.php
=> ISSUE-234: Make Flavor search aware of CWS/Children based OCR

.gitignore, src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php
See #261 
e.g
```JSON
{
"type": "DataSet",
"label": "Title from metadata",
"label_spa": "Título desde metadatos",
"ap:tasks" {
"ap:entitytitle":  "label_spa"
}
}
```
Will yield in an ADO/NODE with title "Título desde metadatos". In case of a wrong JMESPATH expression the original title will be preserved (if existing) or the default label key will be used.
=> ISSUE-261: Adds ap:tasks title source option

config/schema/strawberryfield.schema.yml, src/Form/FilePersisterServiceSettingsForm.php, src/Plugin/QueueWorker/CompostQueueWorker.php
see #265 
This will also always re-enqueue unsafe files and log them. This will at least allow us to show the user these exist and allow an informed decision to be made. @alliomeria @aksm those this sound ok?
Could I get a sanitizing look from you both?
=> ISSUE-265: Allow a workaround for dot files when composting

strawberryfield.module
See #274. The solution is to not allow this, but to re-map them on AMI if we encounter them.
=> ISSUE-274: Remove Islandora remote jpg/tif exceptions

composer.json
Resolves #276.
Tested with various date intervals in facets via JmesPath Strawberry Field Key Name Provider, with the edtf_2_human_date Twig extension, and with the webforms.
=> ISSUE-276: Upgrade EDTF PHP library from 2.0.2 to 3.0.0

config/schema/strawberryfield.schema.yml, src/Form/FilePersisterServiceSettingsForm.php, src/Plugin/QueueWorker/CompostQueueWorker.php, src/StrawberryfieldFilePersisterService.php
See #286 
This adds a new config form element:
And enforces that setting (5 Gbytes by default, the exact default we need) to attempt either a `MultiPart` Upload Operation (with a multipart retry) or a `MultiPart` Copy Operation (between S3 URIs) to manage very large files (basically anything larger to 5 Gbytes if you don't change the default settings.)
Tested and re-retested but might YET again test tomorrow before merging.
=> ISSUE-286: Break the 5 Gbytes barrier without breaking the bank

src/StrawberryfieldFilePersisterService.php
Sorry, follow up on ISSUE-286. This is what happens when I'm solo testing.
Just a small change on how I substitute variables for the logging that happens on Multipart uploads
=> ISSUE-286: Wrong variable substitution on new logs generated by multipart

js/d3viz_strawberryfield.js, src/Form/keyNameProviderOverviewForm.php, strawberryfield.libraries.yml
See #297 
This fixes it.Thanks @alliomeria
=> ISSUE-297: D3JS once v/s Jquery Once fix + small supporting code fixes

src/Plugin/Field/FieldFormatter/StrawberryDefaultFormatter.php
See #303 
Helps fixing issues that kick you (bite and never let you go) when people add  to their JSON HTML tags inside values (and unclosed ones) and the RAW output ends breaking the JS (that is loaded HTML wise after the whole body ..)
Simple little one / smallish fix
=> ISSUE-303: Escape Tags on RAW JSON formatter

strawberryfield.module
See #318. I normally don't chain the accessors like this here, but I can't avoid thinking this might keep happening with mixed Search API + SQL driven views and even more with contributed modules that extend views.
Hope this one fixes the issue for those folks.
=> ISSUE-318: Mixed SQL/SearchAPI driven result sets and Query Object

src/KeyValueStore/DatabaseStorageWithIndex.php, src/KeyValueStore/KeyValueDatabaseWithIndexFactory.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, strawberryfield.services.yml
See #320 
This implements for key/value tables a "wrapper class" that allows listings of existing key values to be made (including get whole/list just the keys) without knowing the actual key name
This is needed to allow our datasource to be re-tracked.
The re-tracker is implemented using the existing interface at ::getPartialItemIds but it does something (i hope) well. It checks if the Nodes/Files associated with a stored SBF Flavor data source entry, still exist. and tries to fill/refill data if a query returns many but none of these are valid... I need to check more because i added a WHILE statement... dangerous stuff. So far so good with my limited to 1500 OCRs test.
@alliomeria @roromedia ping (pong) and ping again
=> ISSUE-320: Adds a new Key value DB class with ranged/listed queries

config/install/search_api_solr.solr_field_type.dense_vector_field_1024_und_9_0_0.yml, config/install/search_api_solr.solr_field_type.dense_vector_field_384_und_9_0_0.yml, config/install/search_api_solr.solr_field_type.dense_vector_field_512_und_9_0_0.yml, config/install/search_api_solr.solr_field_type.dense_vector_field_576_und_9_0_0.yml, src/EventSubscriber/SearchApiSolrEventSubscriber.php, src/Plugin/DataType/StrawberryEntitiesViaJmesPathFromJson.php, src/Plugin/search_api/data_type/DenseVector1024DataType.php, src/Plugin/search_api/data_type/DenseVector384DataType.php, src/Plugin/search_api/data_type/DenseVector512DataType.php, src/Plugin/search_api/data_type/DenseVector576DataType.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/Plugin/search_api/processor/StrawberryFieldHighlight.php, src/StrawberryFieldBreadcrumbBuilder.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
See #325 
This stuff works now.
Requires a fixed entry in schema_extra_fields.xml
like 
```XML
<dynamicField name="knn576m_*" type="knn_vector_576" stored="true" indexed="true" multiValued="false"/>
<dynamicField name="knn576s_*" type="pfloat" stored="true" indexed="true" multiValued="false" />
<dynamicField name="knn512m_*" type="knn_vector_512" stored="true" indexed="true" multiValued="false"/>
<dynamicField name="knn512s_*" type="pfloat" stored="true" indexed="true" multiValued="false" />
<dynamicField name="knn1024m_*" type="knn_vector_1024" stored="true" indexed="true" multiValued="false"/>
<dynamicField name="knn1024s_*" type="pfloat" stored="true" indexed="true" multiValued="false" />
<dynamicField name="knn3846m_*" type="knn_vector_384" stored="true" indexed="true" …
```
=> ISSUE-325: Vectors for each king, one float to rule them all

src/Plugin/Action/StrawberryfieldJsonPatch.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/Plugin/search_api/processor/StrawberryFlavorAggregate.php
See #330 
This also fixes a deprecation VBO introduced where all `action_labels` now need to be `label`. So silly.
=> ISSUE-330: Don't re-track parent Nodes of a flavor if not actively indexing

src/StrawberryfieldFilePersisterService.php
See #344 
This adds `{"ap:tasks": {"ap:forcefilemanage"}}`. If for some reason the original manage attempt of Archipelago fails (means moving to the final location stated inside :
```
"urn:uuid:someuuid": {
"type": "sometime",
"url": "s3:\/\/76f\/somefile-finaldestination-and-desired-location.extension",
"crypHashFunc": "md5",
...
```
Archipelago, for safety will keep using the original location of the file and mark the `file` entity as "permanent" so nobody gets rid of it during CRON temp file disposal. But also permanent means we won't try again (intended)
But of course, IIIF (Cantaloupe) won't be able to access the file and from there one very hard to get it done correctly. This new key allows an ADO to attempt again this even if the File is already Permanent. if the location already …
=> ISSUE-344: allow a file re-manage attempt using ap:task entry

config/install/search_api_solr.solr_field_type.dense_vector_field_768_und_9_0_0.yml, src/Plugin/search_api/data_type/DenseVector768DataType.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
See #347
The new SBF ID structure (for Solr) allows a dash. Only ML generated SBF have this allowing a File level sequence (e.g a PDF, let's say Page 2) to have a subsequence, e.g Annotation 1, 2, 3.
Basically allowing something like this
```JSON
{"id":"3byiu5-default_solr_index-strawberryfield_flavor_datasource/313796:1-2:en:548e48f0-a703-4101-875c-b6f9779c5dbf:chained_mobilenet_child"}
````   
Notice the 
` 313796:1-2` being 313796 the NODE, 1 the File level sequence (1 by default, and -2) being the second annotation generate by an ML Processor
IIIF Content Search API (Format Strawberryfield) will also get a pull to allow that second level one to not confuse the search/matching (tested, works well)
=> ISSUE-347: new Vector (*768) and a new internal sequence for Flavor IDs *using a dash*

composer.json, config/install/search_api_solr.solr_field_type.dense_vector_field_768_und_9_0_0.yml, src/EventSubscriber/StrawberryfieldEventCompostBinSubscriber.php, src/KeyValueStore/DatabaseStorageWithIndex.php, src/Plugin/Field/FieldType/StrawberryFieldItem.php, src/Plugin/search_api/data_type/DenseVector768DataType.php, src/Plugin/search_api/datasource/StrawberryfieldFlavorDatasource.php, src/StrawberryfieldUtilityService.php, src/StrawberryfieldUtilityServiceInterface.php, src/Tools/StrawberryfieldJsonHelper.php, src/TypedData/StrawberryfieldFlavorDataDefinition.php
Adds a helper method that counts Flavours at different hierarchies (Direct, Children, Grandchildren) using configurable OR/AND 
Also adds the 768 Vector, the ability to have sub-flavor ids (needed for ML when a single PDF generates multiple annotations/detections) and some small Release bug fixes when re-tracking Flavour data sources at the Search API index level (we had some WARNINGs there) + Typo corrections
=> ISSUE-349 + 768 Vector

src/Plugin/QueueWorker/CompostQueueWorker.php, strawberryfield.module
See #352 
Added inline comments. Tested ingesting via `drush archipelago:jsonapi-ingest` too. Drupal 10.2 users should not have any issues. But if you are upgrading to 10.3 or 10.4 this is needed to have JSON:API for ADO File uploads working perfectly.
=> ISSUE-352: Composter would not allow JSON API uploaded files to be cleaned + 10.3 JSON API and Field info changes

src/Plugin/QueueWorker/CompostQueueWorker.php, strawberryfield.module
See #352 and #353 for more info. Specially needed if moving to Drupal 10.3+ without updating (at least partially) to Archipelago 1.5.0. This is 10.2 compatible of course
The main issue on 10.4 (tested here, never seen before) is that at the hook_entity_base_field_info() the stream wrapper manager no longer has the "names" for wrappers registered? Of maybe on a local? is using the wrong bits.
JSON API wise, we had to add 'file_extensions' => '' to the field settings, given that 10.3+ JSON API uses the core/standard file controller upload, when before it used to implement a wrapper for the temp file controller (which had no file restrictions).
=> ISSUE-352 (backwards patch for 1.4.0): Composter would not allow JSON API uploaded files to be cleaned + 10.3 JSON API and Field info changes #353
